version: '3.2'
services:
  bitcoin-core:
    image: "owstack/bitcoin-core:0.14.1-ows"
    user: root
    command: "/usr/local/bin/bitcoind -datadir=/data"
    ports:
      - "8332:8332"
      - "8333:8333"
      - "18332:18332"
      - "18333:18333"
      - "28332:28332"
      - "28333:28333"
    volumes:
      - /data/bitcoin-core:/data
  btc-node:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - "bitcoin-core"
    volumes:
      - /data/btc-node:/home/ows/config
    command: "btcnode start -c /home/ows/config -m /home/ows/bitcoin-core-services"
